Add module structure
kkokey/distribute-compute-module pull request #1
Opened 2019-12-17 16:59 UTC by kkokey

- add test

2019-12-17 16:59 UTC, kkokey commented on core/types/module_test.go
> +}
이건 수정중입니다~

2019-12-21 07:08 UTC, jaeryol commented on core/types/module_test.go
> +}
수정되었으면 Resolve 해주세요.

2019-12-21 07:08 UTC, jaeryol commented on core/types/module_test.go
> +
빈 공간 제거해주세요.

2019-12-21 07:09 UTC, jaeryol commented on core/types/module_test.go
> +
빈 공간 제거해주세요.

2019-12-21 07:09 UTC, jaeryol commented on core/types/module_test.go
> +func TestCreateModule(t *testing.T) {
`Creates` 로 변경해주세요.

2019-12-21 07:10 UTC, jaeryol commented on test.sh
> +
6번째 라인 제거해주세요.

2019-12-21 07:10 UTC, jaeryol commented on core/types/module_test.go
> +func TestGetMyIPSuccess(t *testing.T) {
`Gets` 로 변경해주세요.

2019-12-21 07:10 UTC, jaeryol commented on core/types/module.go
> +func (m Module) localIP() (net.IP, error) {
메서드 이름이 `localIP`인 이유는 무엇인가요?
이 메서드의 기능은 무엇인가요?

2019-12-21 07:11 UTC, jaeryongim requested changes
코멘트 확인 부탁드립니다.

2019-12-24 15:01 UTC, kkokey commented on core/types/module.go
> +func (m Module) localIP() (net.IP, error) {
`findLocalIP`로 변경했습니다.

2019-12-24 15:01 UTC, kkokey commented on core/types/module_test.go
> +func TestGetMyIPSuccess(t *testing.T) {
변경 했습니다.

2019-12-24 15:02 UTC, kkokey commented on test.sh
> +
제거했습니다.

2019-12-24 15:02 UTC, kkokey commented on core/types/module_test.go
> +func TestCreateModule(t *testing.T) {
변경했습니다.

2019-12-24 15:02 UTC, kkokey commented on core/types/module_test.go
> +
제거 했습니다.

2019-12-24 15:02 UTC, kkokey commented on core/types/module_test.go
> +
제거 했습니다.

2019-12-25 05:19 UTC, ujuc requested changes

2019-12-25 05:19 UTC, ujuc commented on main.go
> +
빈칸 삭제해주세요.

2019-12-26 03:55 UTC, kkokey commented on main.go
> +
수정 했습니다.

2019-12-27 05:08 UTC, jaeryongim approved these changes

2019-12-27 07:47 UTC, merged